### ISSUE TITLE
Versions Disappear

### ISSUE THREAD

**Issue by M1XT3NZ** [AlphaBs/CmlLib.Core#9]
if you have a version of Minecraft for example 1.16
as a local version.
getting the versions via
 
```
         var infos = MLauncher.UpdateVersions();

            foreach (var item in infos)
            {
               
                if (item.MType == MVersionType.Release)
                    MC_Versions.Items.Add(item.Name);
            }
```

will result in 1.16 to not show up in the list...

I don't expect that this is the expected behavior and its kind of annoying.

**Comment by AlphaBs** [comment]
MVersionLoader cannot parse VersionType when it is local version, because there is no way to get it before parse version file

so just get all local version: 
if (item.IsLocalVersion || item.MType == MVersionType.Release)

or

if (item.IsLocalVersion)
{
MVersion version = infos.GetVersion(item);
if (version.MType == MVersionType.Release)
Something(); // add to list
}
else
Something(); //add to list

**Comment by M1XT3NZ** [comment]
this will actually result in this..
![sorting](https://i.imgur.com/498lStx.png)

//edit while actually writing this

I'm stupid I figured it out. I should've just used 
`MVersionLoader.GetVersionMetadatasFromWeb();`
this will always give the same up2date list. 
:D anyway that works now.. Thanks
